content/docs/nav.yml
content/home/examples/a-component-using-external-plugins.md
content/home/examples/a-simple-component.md
content/home/examples/a-stateful-component.md
content/home/examples/an-application.md
content/home/marketing/component-based.md
content/home/marketing/declarative.md
content/home/marketing/learn-once-write-anywhere.md
src/components/LayoutFooter/Footer.js
src/components/LayoutHeader/DocSearch.js
src/components/LayoutHeader/Header.js
src/pages/index.js

docs(cn): merge discountry/react in this repo

---

content/docs/nav.yml
content/home/examples/a-component-using-external-plugins.md
content/home/examples/a-simple-component.md
content/home/examples/a-stateful-component.md
content/home/examples/an-application.md
content/home/marketing/component-based.md
content/home/marketing/declarative.md
content/home/marketing/learn-once-write-anywhere.md
src/components/LayoutFooter/Footer.js
src/components/LayoutHeader/DocSearch.js
src/components/LayoutHeader/Header.js
src/pages/index.js

Reverts reactjs/cn.reactjs.org#3

Revert "docs(cn): merge discountry/react in this repo"

---

content/docs/code-splitting.md

docs(cn): translate content/docs/code-splitting.md into Chinese

---

content/docs/addons-test-utils.md

docs(cn): translate content/docs/addons-test-utils.md into Chinese

---

content/docs/lists-and-keys.md

docs(cn): translate content/docs/lists-and-keys.md into Chinese

---

content/warnings/unknown-prop.md

https://stackblitz.com/edit/react-unknown-prop
无法重现这个 warning 可能是我例子写得不够高级…

docs(cn): translate content/warnings/unknown-prop.md into Chinese

---

content/docs/conditional-rendering.md

docs(cn): translate content/docs/conditional-rendering.md into Chinese

---

content/docs/react-without-es6.md

docs(cn): add react without es6 translate

---

content/docs/lifting-state-up.md

Review of this PR is welcomed.

docs(cn): translate content/docs/lifting-state-up.md into Chinese

---

content/docs/reference-test-renderer.md

Add Chinese translation for Test Renderer.

docs(cn): translate content/docs/reference-test-renderer.md into Chinese

---

content/docs/reference-react-dom-server.md

translate content/docs/reference-react-dom-server.md into Chinese

docs(cn): translate content/docs/reference-react-dom-server.md into Chinese

---

content/docs/reference-events.md

docs(cn): translate content/docs/reference-events.md into Chinese

---

content/docs/hooks-rules.md

docs(cn): translate content/docs/hooks-rules.md into Chinese

---

content/warnings/special-props.md

https://stackblitz.com/edit/react-special-props
waring 重现

docs(cn): translate content/warnings/special-props.md into Chinese

---

content/warnings/legacy-factories.md

https://stackblitz.com/edit/react-legacy-factories
无法重现这个 warning

docs(cn): translate content/warnings/legacy-factories.md into Chinese

---

content/warnings/invalid-aria-prop.md

https://stackblitz.com/edit/react-invalid-aria-prop
warning 重现
因为单词缩写太长 做了一些结构性调整（参考人家俄文的调整…）

docs(cn): translate content/warnings/invalid-aria-prop.md into Chinese

---

content/warnings/dont-call-proptypes.md

https://stackblitz.com/edit/react-dont-call-proptypes
warning (crash) 重现
call XX
这里的 call 应该是指 JS 里的函数/方法调用
那么我统一翻译成 `调用 XX 函数`

docs(cn): translate content/warnings/dont-call-proptypes.md into Chinese

---

content/docs/jsx-in-depth.md

Any review and translation optimization recommendation is welcomed.

docs(cn): translate content/docs/jsx-in-depth.md into Chinese

---

content/docs/faq-internals.md

 docs(cn)/faq-internals-translation

---

content/docs/typechecking-with-proptypes.md

docs Typechecking With PropTypes

---

content/docs/fragments.md

docs(cn): translated content/docs/fragments.md into Chinese

---

content/docs/handling-events.md

`this` 绑定在 `handleClick` 内听起来很奇怪，通常来说 `this` 被绑定指的是上下文绑定了（例如这里应该说绑定了当前 `class`）。

fix(docs):  modify the comment for content/docs/handling-events.md

---

content/docs/jsx-in-depth.md

In English:
For example, this code will not behave as you might expect because **0 will be printed** when props.messages is an empty array:
是 **0会被渲染** 而不是 ~~\<MessageList /\>会被渲染~~

fix(docs): translate error in jsx-in-depth

---

content/docs/faq-ajax.md

docs(cn): translate docs/faq-ajax.md into Chinese

---

content/docs/faq-build.md

docs(cn): translate content/docs/faq-build.md into Chinese

---

content/docs/web-components.md

docs(cn): translate docs/web-components into Chinese

---

content/docs/faq-styling.md

docs(cn): translate content/docs/faq-styling.md into Chinese

---

content/blog/2013-06-05-why-react.md

docs(cn): translate content/blog/2013-06-05-why-react.md into Chinese

---

content/docs/hooks-state.md

原文是双引号 ”hook into“，不是代码 `hook into`。
The original words are "hook into", not `hook into`.

docs(cn): fix punctuation error in content/docs/hooks-state.md

---

content/docs/portals.md

docs(cn): translate content/docs/portals.md into Chinese

---

content/docs/reference-react-component.md

docs(cn): fix link in content/docs/reference-react-component.md

---

content/docs/hooks-reference.md

docs(cn): delete extra periods in  content/docs/hooks-reference.md

---

content/docs/static-type-checking.md

> [original](https://reactjs.org/docs/static-type-checking.html)

docs(cn): definitely typed is developed at Microsoft, not WeChat in content/docs/static-type-checking.md

---

content/tutorial/tutorial.md

fixed case spelling errors
onCLick ==> onClick
thanks!

docs(cn): fixed spelling errors in docs/content/tutorial/tutorial.md

---

content/docs/reference-dom-elements.md

`suppressContentEditableWarning`的作用是取消设置`contentEditable`导致的警告。
原文‘This attribute suppresses that warning’也是取消该警告的意思，感觉翻译成“此属性会触发警告信息”意思相反了，或者存在歧义。

docs(cn): modify the explanation for suppress in content/docs/reference-dom-elements.md

---

content/docs/faq-versioning.md

docs(cn): translate content/docs/faq-versioning.md into Chinese

---

content/tutorial/tutorial.md

docs(cn): remove extra Chinese commas in content/tutorial/tutorial.md

---

content/tutorial/tutorial.md

docs(cn): fix wrong spelling in content/tutorial/tutorial.md

---

content/tutorial/tutorial.md

replace helper with calculateWinner.

docs(cn): fix the misleading function name in content/tutorial/tutorial.md

---

content/docs/hooks-faq.md

语义不太对，原文是 the alert will show the count variable at the time you clicked the “Show alert” button.
意思是 alert 会显示点击按钮时的 count 变量，而不是「 alert 会 在你点击『Show alert』按钮时 显示 count 变量」

docs(cn): modify semantic errors in content/docs/hooks-faq.md

---

content/docs/hooks-faq.md

英文原文：
Specifying [count] as a list of dependencies would fix the bug, but would cause the interval to be reset on every change.
[link](https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often)
当前翻译：
指定 [count] 作为依赖列表就能修复这个 Bug，但会导致内部每次改变时都被重置。
[link](https://react.docschina.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often)
更正：
指定 [count] 作为依赖列表就能修复这个 Bug，但会导致每次改变发生时定时器都被重置。
interval 不应翻译成内部而是定时器

docs(cn): fix translation word error in content/docs/hooks-faq.md

---

content/docs/state-and-lifecycle.md

卸载的单词应该是【unmount】，而不是【umount】。

docs(cn): fix word spell error in content/docs/state-and-lifecycle.md

---

content/docs/hooks-overview.md

```
In this example, React would unsubscribe from our ChatAPI when the component unmounts, as well as before re-running the effect due to a subsequent render.
```
应该是：
在这个示例中，React 会在组件销毁时取消对 `ChatAPI` 的订阅，然后在后续渲染时重新执行副作用函数。

docs(cn): adjust sentence in content/docs/hooks-overview.md

---

content/docs/context.md

按照原文（英文）的意思，只有将 `undefined` 的 value 传递给 Provider 时，消费 context 的组件的 defaultValue 才不会生效。
而翻译中没有提到 Provider 的 value，不够清楚。

docs(cn): update React.createContext in content/docs/context.md

---

content/docs/hooks-reference.md

docs(cn): fix characters error in  content/docs/hooks-reference.md

---

examples/forwarding-refs/log-props-after.js

docs(cn): fix word in examples/forwarding-refs/log-props-after.js

---

content/docs/forwarding-refs.md

docs(cn): fix word in content/docs/forwarding-refs.md

---

content/docs/reference-test-renderer.md

translate the missing part of content/docs/reference-test-renderer.md

docs(cn): translate mssing part of test render

---

content/blog/2018-06-07-you-probably-dont-need-derived-state.md

1. fix typo `应为` to `因为`;
2. remove an extra space after `派生` which causes that phrase is not be rendered in bold font.

docs(cn): fix typo in content/blog/2018-06-07-you-probably-not-need-derived-state.md

---

content/docs/hooks-reference.md

fix Page Not Found
[Hook API 索引](https://zh-hans.reactjs.org/docs/hooks-reference.html#usecontext)

docs(cn): fix errors in content/docs/hooks-reference.md

---

content/tutorial/tutorial.md

remove first 代 in 我们需要修改代 Square 的代码

docs(cn): remove wrong tralation in content/tutorial/tutorial.md

---

content/docs/hooks-effect.md
content/docs/hooks-state.md

发现了两处错误。
读文档的时候感觉 “部分” 这两个字放后面有点歧义，放前面是不是好些？

docs(cn): fix errors in hooks-effect.md&hooks-state.md

---

content/docs/hooks-effect.md

original text: you might be wondering why the effect cleanup phase happens after every re-render

docs(cn): fix some words lack cause meaning mistake in content/docs/hooks-effect.md

---

content/docs/forms.md

英文: `Specifying the value prop on a controlled component prevents the user from changing the input unless you desire so. If you’ve specified a value but the input is still editable, you may have accidentally set value to undefined or null.`
把“可以防止”改成“会阻止“，这更容易理解。
原文中的”你“不该省略。这里的”你“就强调读这段文字的人。

Change Chinese translation

---

content/docs/legacy-context.md

translate content/docs/legacy-context.md into Chinese

docs(cn): translate content/docs/legacy-context.md into Chinese

---

content/docs/forms.md

Double quotation marks in English here

fix: quote mark error in content/docs/forms.md

---

content/docs/render-props.md

Change :
组件是 React 代码复用的主要单元，_但如何分享一个组件封装到其他需要相同 state 组件的状态或行为并不总是很容易。_
To:
组件是 React 代码复用的主要单元，_但如何将一个组件封装的状态或行为共享给其他需要相同状态的组件并不总是显而易见。_

docs(cn): optimize semantics in content/docs/render-props.md

---

content/docs/render-props.md

English version: Here’s where the render prop comes in: Instead of hard-coding a <Cat> inside a <Mouse> component, and effectively changing its rendered output, we can provide <Mouse> with a function prop that it uses to dynamically determine what to render–a render prop.
Old version: 这也是 render prop 的来历：我们可以提供一个带有函数 prop 的 `<Mouse>` 组件，它能够动态决定什么需要渲染的，而不是将 `<Cat>` 硬编码到 `<Mouse>` 组件里，并有效地改变它的渲染结果。
New version: 相比于直接将 `<Cat>` 写死在 `<Mouse>` 组件中，并且有效的更改渲染的结果，我们可以为 `<Mouse>` 提供一个函数 prop 来动态的确定要渲染什么 – 一个 render prop

docs(cn): fix render props translation

---

content/docs/context.md

194行删除多余的等字
Note to Hacktoberfest 🎃 participants:
While we appreciate the enthusiasm, we are experiencing a high volume of drive-by pull requests (one-line changes, README tweaks, etc.). Please remember that hundreds of people are subscribed to this repo and will receive notifications for these PRs. Spam submissions will be closed and won't count towards your Hacktoberfest goals.
Please search for issues tagged [`good first issue`][gfi] or [`hacktoberfest`][hacktoberfest] to find things to work on.
You can also search [all of GitHub][all].
[gfi]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[hacktoberfest]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[all]: …

docs(cn): fix word in content/docs/context.md

---

content/docs/forwarding-refs.md

The code snippet is at the bottom of the text, so the descriptor should use "下面"

docs(cn): fix some text in content/docs/forwarding-refs.md

---

content/docs/design-principles.md

"我们倾听者大家的痛点"  => "我们倾听着大家的痛点" at [/master/content/docs/design-principles.md]()
【者】=>【着】

docs(cn): fix the wrongly written or characters in zh-cn

---

content/docs/render-props.md

It's more appropriate to translate "extend" into "继承" rather than "扩展" .

docs(cn): fix word in content/docs/render-props.md

---

content/docs/render-props.md

原文是"close over",有"掩盖"的意思,例子将直接暴露的state改为了只暴露需要的state,因此翻译为"控制暴露程度"更便于理解

docs(cn): fix words content/docs/render-props.md

---

content/docs/hooks-reference.md

original doc says:`The returned object will persist for the full lifetime of the component.`, emphasize **"persist"**
but the word `保持不变` means `"stay unchanged"` which is inappropriate under the circumstances

docs(cn): fix translation for persisit

---

content/docs/context.md

The lack of verbs makes this sentence look a bit strange

docs(cn): optimized expression in content/docs/context.md

---

content/docs/hooks-faq.md

一般情况下，“其它”同“其他”。但在使用上还是有一些小区别的。正常情况下，“其它”只用于事情。另外，在人与动物方面，也有区别。如我们说其他同志而不能说其它同志；再如，我们说其它动物，而不说其他动物（拟人化的童话故事、小说除外）

docs(cn): fix words in content/docs/hooks-faq.md

---

content/tutorial/tutorial.md

段落里提到，回调函数会触发**弹出框**，实际上该函数只有**控制台输出**

docs(cn): optimized translation in content/tutorial/tutorial.md

---

content/docs/higher-order-components.md

In Chinese version of this page, the code comment about EnhancedComponent is confused. We are used to talk about "instead of" after the "suggested way" in Chinese. So, I suggested the docs use another sentence(or, description) in the code comment here. And I provided a better description way.

docs(cn): adjust the statement in content/docs/higher-order-components.md

---

content/docs/code-splitting.md

原文:
> Here, you tell React that setting tab to `'comments'` is not an urgent update, but is a [transition](https://reactjs.org/docs/react-api.html#transitions) that may take some time. React will then keep the old UI in place and interactive, and will switch to showing `<Comments />` when it is ready. See [Transitions](https://reactjs.org/docs/react-api.html#transitions) for more info.
原翻译:
> 此处代码会告知 React，将标签设置为 `'comments'`，并非一个紧急更新。而是一个 [transition](https://zh-hans.reactjs.org/docs/react-api.html#transitions)，可能需要一些实际。然后 React 会保留旧的 UI 并进行交互，当它准备好时，会切换为 `<Comments />`，具体请参阅 [Transitions](https://zh-hans.reactjs.org/docs/react-api.html#transitions) 以了解更多相关信息。
现修改为:
> 此处代码会告知 React，将标签切换为 `'comments'` 不会标记为紧急更新，而是标记为需要一些准备时间的 [transition](https://zh-hans.reactjs.org/docs/react-api.html#tr …

docs(cn): fix a typo and improve accuracy

---

content/docs/introducing-jsx.md

1. “进行”强调一种动作，而“……到文件中”是一种结果。所以不宜一起使用。
2. “分离方式”是名词，应使用“的”来进行修饰。

docs(cn): fix typo in introducing-jsx.md

---

content/docs/conditional-rendering.md

docs(cn): add link to falsy expressions but do not translate

---

content/docs/hooks-reference.md

fix the wrong translation of hooks-reference

docs(cn): fix wrong translation

---

content/docs/jsx-in-depth.md

The English version:
For example, this code will not behave as you might expect because 0 will be printed when props.messages is an empty array:
The Chineses version:
例如，以下代码并不会像你预期那样工作，因为当 props.messages 是空数组时，0 仍然会被渲染：
呃，讲中文吧。
上一段示例在讲`{showHeader && <Header />}`，到这一段来个`仍然会被渲染`，还以为讲的是`MessageList`组件仍然会被渲染，容易理解错

docs(cn): fix a confusing statement

---

beta/src/content/learn/start-a-new-react-project.md

更改前：主流的包管理器有：[npm](https://www.npmjs.com/)（内置于 Node.js）中，[Yarn](https://yarnpkg.com/)，[pnpm](https://pnpm.io/)。
更改后：主流的包管理器有：[npm](https://www.npmjs.com/)（内置于 Node.js中），[Yarn](https://yarnpkg.com/)，[pnpm](https://pnpm.io/)。

fix(cn): description error

---

content/docs/hooks-reference.md

Fix a spelling error in the Chinese documentation of Hooks API Reference

fix: Fix a spelling error in the Chinese document

---

content/blog/2018-06-07-you-probably-dont-need-derived-state.md

在整个表单上添加 key 更有位合理  --> 在整个表单上添加 key 更为合理

fix typo in `2018-06-07-you-probably-dont-need-derived-state`

---

beta/src/content/learn/extracting-state-logic-into-a-reducer.md

这两句话是不是翻译时漏掉了，简单翻译了一下不知道是否合适。
Then you can replace `useState`:
```js
const [tasks, setTasks] = useState(initialTasks);
```
with `useReducer` like so:
```js
const [tasks, dispatch] = useReducer(tasksReducer, initialTasks);
```
接下来，你就可以替换掉之前的 `useState`:
```js
const [tasks, setTasks] = useState(initialTasks);
```
只需要像下面这样使用 `useReducer`:
```js
const [tasks, dispatch] = useReducer(tasksReducer, initialTasks);
```

fix(cn): lack of translation

---

beta/src/content/learn/render-and-commit.md

Markdown有一处忘记空格了。
更改前：
**React 仅在渲染之间存在差异时才会更改 DOM 节点。**例如，有一个组件，它每秒使用从父组件传递下来的不同属性重新渲染一次。注意，您可以添加一些文本到 `<input>` 标签，更新它的 `value`，但是文本不会在组件重渲染时消失：
更改后：
**React 仅在渲染之间存在差异时才会更改 DOM 节点。** 例如，有一个组件，它每秒使用从父组件传递下来的不同属性重新渲染一次。注意，您可以添加一些文本到 `<input>` 标签，更新它的 `value`，但是文本不会在组件重渲染时消失：

fit(cn): md incorrect usage

---

beta/src/content/learn/writing-markup-with-jsx.md

有一小段内容没有翻译，不知是不是被遗漏了，简单进行了一下翻译不知道合不合适。
更改前：
But as the Web became more interactive, logic increasingly determined content. JavaScript was in charge of the HTML! This is why **in React, rendering logic and markup live together in the same place—components.**
更改后：
但随着 Web 的交互性越来越强，逻辑越来越决定页面中的内容。JavaScript 需要对 HTML 负责！这也是为什么 **在 React 中，渲染逻辑和标记共同存在于同一个地方——组件。**

fit(cn): lack of translation

---

src/content/learn/extracting-state-logic-into-a-reducer.md
src/content/learn/manipulating-the-dom-with-refs.md
src/content/learn/reacting-to-input-with-state.md
src/content/learn/state-a-components-memory.md
src/content/learn/state-as-a-snapshot.md

**Description:** I found some markdown-bold problems in some page, like this
[State：组件的记忆-State 是隔离且私有的](https://zh-hans.react.dev/learn/state-a-components-memory#state-is-isolated-and-private)

docs: fix markdown-bold invalid

---

src/content/reference/react/useImperativeHandle.md

docs(cn): translate reference/react/useImperativeHandle into Chinese

---

src/content/reference/react/useRef.md

docs(cn): translate reference/react/useRef into Chinese

---

src/content/reference/react/createRef.md

docs(cn): translate reference/react/createRef into Chinese 

---

src/content/learn/state-a-components-memory.md

This PR fixes this [issue](https://github.com/reactjs/react.dev/issues/6085)

fix: fix redirect link to `state-as-a-snapshot`

---

src/content/reference/react-dom/server/renderToStaticMarkup.md

docs(cn): translate renderToStaticMarkup into Chinese

---

src/content/reference/react-dom/components/option.md

翻译 reference/react-dom/components/option。

docs(cn): translate reference/react-dom/components/option into Chinese

---

src/content/reference/react-dom/server/renderToStaticNodeStream.md

翻译 reference/react-dom/server/renderToStaticNodeStream。

docs(cn): translate reference/react-dom/server/renderToStaticNodeStream into Chinese

---

src/content/reference/react-dom/server/renderToNodeStream.md

翻译：reference/react-dom/server/renderToNodeStream。

docs(cn): translate reference/react-dom/server/renderToNodeStream into Chinese

---

src/content/reference/react-dom/unmountComponentAtNode.md

翻译 reference/react-dom/unmountComponentAtNode。

docs(cn): translate reference/react-dom/unmountComponentAtNode into Chinese

---

src/content/reference/react/cloneElement.md

docs(cn): translate reference/react/cloneElement into Chinese

docs(cn): translate reference/react/cloneElement into Chinese

---

src/content/reference/react/PureComponent.md

翻译 reference/react/PureComponent

docs(cn): translate reference/react/PureComponent into Chinese

---

src/content/warnings/unknown-prop.md

docs(cn): translate warnings/unknown-prop into Chinese

---

src/content/reference/react/createElement.md

docs(cn): translate legacy/createElement into Chinese

---

src/content/reference/react-dom/components/index.md

翻译 reference/react-dom/components/index。

docs(cn): translate reference/react-dom/components/index into Chinese

---

src/content/reference/react/legacy.md

docs(cn): translate reference/react/legacy into Chinese

---

src/content/blog/2021/06/08/the-plan-for-react-18.md

1. 移除多余的 2021
2. 删除 “由...发布。” 和其他博客翻译形式保持一致

fix: optimize a translation of blog's meta info

---

src/content/learn/synchronizing-with-effects.md

翻译 learn/synchronizing-with-effects。

docs(cn): translate learn/synchronizing-with-effects into Chinese

---

src/content/learn/synchronizing-with-effects.md
src/sidebarLearn.json

Corrected **sidebar** title and **main text** for `learn/synchronizing-with-effects`

docs(cn): update learn/synchronizing-with-effects translation

---

src/content/learn/updating-arrays-in-state.md

This PR addresses [Issue #6200 in the main `react.dev` repo](https://github.com/reactjs/react.dev/issues/6200) by fixing a broken link where the prefix `docs` is used instead of `learn`

fix: a broken link

---

src/content/reference/react/useEffect.md

原文的含义应该是"useEffect在组件挂载到 DOM 之后执行"

fix: fix useEffect translation

---

src/content/learn/synchronizing-with-effects.md

Corrected two translation errors in learn/synchronizing-with-effects.
错误在learn/synchronizing-with-effects
original:
1.When [Strict Mode](https://react.dev/reference/react/StrictMode) is on, React remounts every component once after mount (state and DOM are preserved).
2.Fetching 'Taylor' completes before fetching 'Bob'

docs(cn): correct learn/synchronizing-with-effects translations

---

src/content/learn/synchronizing-with-effects.md

英文版本：
> If you don’t want some code to re-run, [edit the Effect code itself to not “need” that dependency.](https://react.dev/learn/lifecycle-of-reactive-effects#what-to-do-when-you-dont-want-to-re-synchronize)
线上的翻译：
> 如果你希望重复执行...
所以做了优化~

fix: correct translations

---

src/content/learn/you-might-not-need-an-effect.md

原文：
> In the Buy button click event handler, you know exactly what happened. By the time an Effect runs, you don’t know what the user did (for example, which button was clicked).
我觉得原文是想强调：在事件的回调函数里，我们自然地知晓发生了什么，因为我们查看这个事件回调函数由哪个事件触发的就一目了然。但是如果此时有一个Effect运行了，我们无法根据这个Effect来推断出，用户到底做了什么。
线上的翻译我读上去总觉得有点别扭，感觉没有表达出英文想表达的~

docs(cn): improve learn/you-might-need-an-effect translation

---

src/content/reference/react-dom/hooks/index.md

翻译 reference/react-dom/hooks/index。

docs(cn): translate reference/react-dom/hooks/index into Chinese

---

src/content/reference/react-dom/hooks/useFormStatus.md

翻译 reference/react-dom/useFormStatus。

docs(cn): translate reference/react-dom/useFormStatus into Chinese

---

src/content/reference/react/experimental_taintObjectReference.md
src/content/reference/react/experimental_taintUniqueValue.md

规范 `taint` 的中文翻译，见 https://github.com/reactjs/zh-hans.react.dev/issues/1359 。

docs(cn): standardize the translations of the word taint

---

src/content/reference/react/hooks.md
src/sidebarReference.json

翻译 reference/react/hooks。
刚才注意到这一篇没有翻译，但是我印象中是翻译过一遍的，感觉像是某次合并冲突的时候被直接覆盖了，可以找找之前的翻译。

docs(cn): translate reference/react/hooks into Chinese

---

src/content/learn/lifecycle-of-reactive-effects.md

`代码中的每个 Effect 应该代表一个独立的同步过程。. ` -> 
`代码中的每个 Effect 应该代表一个独立的同步过程。`

fix: remove redundant punctuation

---

src/content/reference/react/directives.md
src/content/reference/react/index.md
src/content/reference/react/use-client.md
src/content/reference/react/use-server.md
src/sidebarReference.json

docs(cn): update the translations of directive

---

src/content/reference/react/use-client.md
src/content/reference/react/use-server.md

翻译 `use-server` 与 `use-client` 的 title tag。

docs(cn): translate title tag of use-server and use-client

---

src/content/reference/react-dom/client/createRoot.md

Fix a typo in a URL at [`/reference/react-dom/client/createRoot`](https://zh-hans.react.dev/reference/react-dom/client/createRoot#parameters).
Fixes reactjs/react.dev#6448.

docs(cn): fix typo in URL

---

src/content/reference/react/useCallback.md

表达和英文没有对应上，英文是"React will return (not call!) your function back to you during the initial render."，强调不是直接调用这个函数，而是返回这个函数。

docs(cn): fix useCallback translation

---

src/content/learn/extracting-state-logic-into-a-reducer.md

在 src\content\learn\extracting-state-logic-into-a-reducer.md 文件的“编写一个好的 reducers”章节中，“`reducers` 在是在渲染时运行的”该句多了一个”在”。

fix typo in extracting-state-logic-into-a-reducer.md

---

src/content/reference/react/use.md

fix: typo in use.md

---

src/content/learn/describing-the-ui.md
src/sidebarLearn.json

before:
current:
全部统一翻译成 `描述 UI`
理念：UI 这种词汇个人理解不需要使用 user interface 来进行翻译

fix: unify the translation of `describing-the-ui`

---

src/content/reference/react/useImperativeHandle.md

fix: typo in useImperativeHandle.md

---

src/content/learn/typescript.md

原文：
> A more explicit alternative to setting the type on `initialState` is to provide a type argument to `useReducer`:

fix: translation

---

src/content/learn/escape-hatches.md
src/sidebarLearn.json

由于原文标题在之前 #1590 已做修改，同步更新其他文件中的锚文本。

fix: Modify the anchor text “使用 Effect 同步”

---

src/content/learn/reusing-logic-with-custom-hooks.md

现在的翻译并不通顺，阅读原文后，发现英文版本是：
> There is a number of edge cases it doesn’t consider. For example, it assumes that when the component mounts, isOnline is already true, but this may be wrong if the network already went offline. 
1. `assume`我觉得翻译成**认为**读起来更通顺。
2. 增加了**它**主语，否则读起来真的很迷惑。

docs(cn): improve learn/reusing-logic-with-custom-hooks translation 

---

src/components/MDX/ExpandableCallout.tsx
src/content/reference/rsc/server-components.md
src/sidebarReference.json

@Yucohny @loveloki @awxiaoxian2020 Please review my translation. If there's any error or typo, please let me know, I'll fix as soon as possible.

docs(cn): translate reference/rsc/server-components into Chinese

---

src/content/learn/installation.md

docs: translate installation

---

src/content/learn/index.md

- 原文：` we're moving code from here`
- 原译文：`我们将把代码移动到这里`
- 现译文：`我们正在从这里移动代码`
`from` 的意思是 `从`，而不是 `到`。

fix: meaning error in learn

---

src/content/learn/separating-events-from-effects.md

Update translation and fix format issue for `separating-events-from-effects.md`
- Added missing translations
- Unified spacing rules
Reference:

docs(cn): update translation and fix format issue

---

src/content/learn/removing-effect-dependencies.md

This PR focuses on:
- Fixing a translation error:
The original English text:
> Now that `roomId` is not a reactive value (and can’t change on a re-render), it doesn’t need to be a dependency:`
Correct translation:
现在 `roomId` 不是响应式值（并且不会在重新渲染时改变），因此它**不需要作为**依赖项：
I believe the previous translation "那它不就不是依赖" is a typo, and this PR corrects it.
- Unifying spacing rules:
Added a space after English words to align with the spacing conventions across the document, ensuring consistency and better readability.

fix(cn): Fix translation error and align with the spacing conventions

---

src/content/learn/reusing-logic-with-custom-hooks.md

This PR addresses three improvements:
1. Updates Chinese translation for better accuracy
2. Standardizes spacing to follow project conventions
3. Corrects variable name typo: `ServeUrl` → `serverUrl` (missing 'r')

docs(cn): fix typo and standardize spacing

---

src/content/learn/index.md

[As shown in the attached screenshot](https://zh-hans.react.dev/learn#components), one of the external links still points to the English version of **javascript.info,** while the **MDN** link already points to the Simplified Chinese page.
This PR updates the **javascript.info** link to its Simplified Chinese version for consistency:
https://javascript.info/import-export -> https://zh.javascript.info/import-export

docs: Fix external link to zh.javascript.info

---

.github/workflows/analyze_comment.yml
src/content/reference/react/cache.md

docs: fix markdown link

---

src/content/reference/react/memo.md

[translate part link](https://zh-hans.react.dev/reference/react/memo)

docs: add translate in memo.md 

---

src/content/reference/react/startTransition.md

[add translate page link](https://zh-hans.react.dev/reference/react/startTransition#caveats)

docs: add translate in  /reference/react/startTransition.md

---

src/content/learn/react-compiler/index.md

[translate page link](https://zh-hans.react.dev/learn/react-compiler)
我不确定Shipping该翻译成什么？词典介绍为航运，运输。
breaking patterns 可以直接翻译成破坏模式吗？

docs(cn): translate /learn/react-compiler/index.md into Chinese

---

src/content/reference/react-dom/static/prerender.md

[translate page link](https://zh-hans.react.dev/reference/react-dom/static/prerender)

docs: add translate in prerender.md
