reactjs/zh-hans.react.dev

- content/docs/nav.yml
- content/home/examples/a-component-using-external-plugins.md
- content/home/examples/a-simple-component.md
- content/home/examples/a-stateful-component.md
- content/home/examples/an-application.md
- content/home/marketing/component-based.md
- content/home/marketing/declarative.md
- content/home/marketing/learn-once-write-anywhere.md
- src/components/LayoutFooter/Footer.js
- src/components/LayoutHeader/DocSearch.js
- src/components/LayoutHeader/Header.js
- src/pages/index.js
> docs(cn): merge discountry/react 

- content/docs/cdn-links.md
> docs(cn): translate content/docs/cdn-links.md into Chinese

- src/components/CodeExample/CodeExample.js
> 翻译 CodeExample

- src/components/CodeEditor/CodeEditor.js
> docs(cn): translate src/components/CodeEditor/CodeEditor.js

- content/docs/reference-react.md
Any review and translation optimization recommendation is welcomed.
> **Note**
> - `Line 189`
> - Part begin with `Line 300` about `React.forwardRef`
>
> These two parts in the doc need more focus during reviewing, thanks.
> docs(cn): translate content/docs/reference-react.md into Chinese

- content/docs/hooks-state.md
Finish translate hooks-state.md. Please review it.
> fix(cn): modify errors in translation

- content/docs/reference-react-component.md
- examples/react-component-reference/get-snapshot-before-update.js
> docs(cn): translate/content/docs/reference-react-component.md into Chinese

- content/docs/reconciliation.md
> doc: Chinese translation for reconciliation.md

- content/docs/reference-react-component.md
> fix(docs): fix typo in reference-react-component.md

- content/docs/jsx-in-depth.md
> fixs(docs): translate error of content/docs/jsx-in-depth

- content/docs/components-and-props.md
- content/docs/hello-world.md
- content/docs/introducing-jsx.md
- content/docs/uncontrolled-components.md
- gatsby-config.js
> docs(cn): fix the display of the codepen in the page

- content/docs/react-without-jsx.md
> docs(cn): translate content/docs/react-without-jsx.md into Chinese

- content/docs/handling-events.md
> fix: correct some spelling mistakes in handling-events.md

- content/docs/lists-and-keys.md
> docs(cn): fix display error in content/docs/list-and-keys.md

- content/docs/lists-and-keys.md
- content/docs/nav.yml
> docs(cn): lint text style in content/docs/list-and-keys.md

- content/tutorial/tutorial.md
> docs(cn): change '0' to 'O' in content/tutorial/tutorial.md

- content/docs/hooks-reference.md
> docs(cn): revise content/docs/hooks-reference.md 

- content/docs/hooks-state.md
> docs(cn): revise content/docs/hooks-state.md

- content/tutorial/tutorial.md
line 267 : 组件构的造函数 => 组件的构造函数
line 461 : 代表事件的的监听 => 代表事件的监听
> docs(cn): two small problems in content/tutorial/tutorial.md

- content/docs/hooks-faq.md
阅读到此处，觉得 “声明” 要比 “申明” 更准确一点。
[中文原文:](https://zh-hans.reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often)
[英文原文:](https://reactjs.org/docs/hooks-faq.html#can-i-skip-an-effect-on-updates)
> docs(cn): change word in content/docs/hooks-faq.md

- content/docs/hooks-custom.md
> docs(cn): revise  content/docs/hooks-custom.md

- content/docs/hooks-effect.md
- content/docs/hooks-overview.md
'First' means '首先', not '首页', the orgin url: https://reactjs.org/docs/hooks-overview.html#building-your-own-hooks
> Spelling mistake

- content/docs/integrating-with-other-libraries.md
> docs(cn): revise content/docs/integrating-with-other-libraries.md

- content/docs/hooks-reference.md
> docs(cn): add missing character in content/docs/hooks-reference.md

- content/docs/forms.md
> docs(cn): revise content/docs/forms.md

- content/docs/render-props.md
> docs(cn): fix word order in content/docs/render-props.md

- content/docs/accessibility.md
> docs(cn): fix typo in docs/content/docs/accessibility.md

- content/docs/hooks-overview.md
> fix: Update hooks-overview.md

- content/docs/handling-events.md
I guess react it is not exactly the opposite, but the  way the react is used
> docs(cn): revise word in content/docs/handling-events.md

- content/docs/reference-react-component.md
> docs(cn): revise word in content/docs/reference-react-component.md

- src/components/LayoutFooter/Footer.js
> docs(cn): add qr code in project

- content/docs/higher-order-components.md
> docs(cn): fix typos in content/docs/higher-order-components.md

- content/docs/error-boundaries.md
> docs(cn): fix link address error incontent/docs/error-boundaries.md

- content/docs/state-and-lifecycle.md
> docs: rm space in content/docs/state-and-lifecycle.md

- content/docs/state-and-lifecycle.md
> docs(cn): fix arrow function mdn links in content/docs/state-and-lifecycle.md

- content/docs/state-and-lifecycle.md
> docs(cn): delete a few extra spaces in content/docs/state-and-lifecycle.md

- content/blog/2019-08-08-react-v16.9.0.md
> docs: translate content/docs/content/blog/2019-08-08-react-v16.9.0.md into Chinese

- content/docs/codebase-overview.md
> docs(cn): fix words in content/docs/codebase-overview.md

- content/docs/reference-profiler.md
> docs(cn): translate content/docs/reference-profiler.md into Chinese

- content/blog/2019-08-15-new-react-devtools.md
> docs(cn): translate content/blog/2019-08-15-new-react-devtools.md into Chinese

- content/blog/2019-08-15-new-react-devtools.md
> docs(cn):fix firefox misspelled

- content/docs/lists-and-keys.md
Delete a few extra spaces in content/docs/lists-and-keys.md
> docs(cn): delete a few extra spaces in content/docs/lists-and-keys.md

- content/docs/lists-and-keys.md
> docs(cn): fix speech error in content/docs/lists-and-keys.md

- content/blog/2018-10-01-create-react-app-v2.md
> docs(cn): translate content/blog/2018-10-01-create-react-app-v2.md into Chinese

- content/docs/jsx-in-depth.md
> docs(cn): fix error in docs/jsx-in-depth.md

- content/docs/hooks-custom.md
> docs(cn): fix words in content/docs/hooks-custom.md

- content/docs/uncontrolled-components.md
> docs(cn): fix error in content/docs/uncontrolled-components.md

- content/docs/reference-react-component.md
> docs(cn): fix errors in reference-react-component.md

- content/docs/higher-order-components.md
Just change the translation as original confuses me.
> docs(cn): change translation in content/docs/higher-order-components.md

- content/blog/2019-02-06-react-v16.8.0.md
大佬们，[之前的PR](https://github.com/reactjs/zh-hans.reactjs.org/pull/171) 的原分支被我误删了．orz
这个是提了个新的 PR，之前提到的改动建议已经修改，实在不好意思
> docs(cn): translate content/blog/2019-02-06-react-v16.8.0.md into Chinese 

- content/blog/2016-01-12-discontinuing-ie8-support.md
Translation complete, let me know if any modification is needed!
> docs(cn): translate content/blog/2016-01-12-discontinuing-ie8-support.md into Chinese

- content/docs/hooks-reference.md
> doc(cn): fix error in hooks-reference.md

- content/docs/addons-test-utils.md
> docs(cn): fix Enzyme link in content/docs/addons-test-utils.md

- content/docs/jsx-in-depth.md
> docs(cn): fix words in content/docs/jsx-in-depth.md

- content/docs/hooks-state.md
> docs(cn): fix word in content/docs/hooks-state.md

- content/tutorial/tutorial.md
跟踪数据的改变需要可变对象可以与之改变之前的版本进行对比  **改为**  跟踪数据的改变需要可变对象可以与改变之前的版本进行对比
[🔗](https://zh-hans.reactjs.org/tutorial/tutorial.html#detecting-changes)
> docs(cn): remove wrong tralation in content/tutorial/tutorial.md

- content/blog/2013-08-19-use-react-and-jsx-in-python-applications.md
Finished translating doc 2013-08-19-use-react-and-jsx-in-python-applications.md into Chinese
> docs(cn): translate content/blog/2013-08-19-use-react-and-jsx-in-python-applications.md into Chinese

- content/docs/release-channels.md
> docs(cn): translate content/docs/release-channels.md into Chinese

- content/blog/2018-10-23-react-v-16-6.md
> docs(cn): translate content/blog/2018-10-23-react-v-16-6.md into Chinese

- content/docs/how-to-contribute.md
- examples/context/theme-detailed-app.js
> docs(cn): fix build error

- content/docs/concurrent-mode-patterns.md
- examples/context/theme-detailed-app.js
> docs(cn): fix some error in content/docs/concurrent-mode-patterns.md

- content/blog/2018-06-07-you-probably-dont-need-derived-state.md
> docs(cn): fix some error in blog/2018/06/07/you-probably-dont-need-derived-state.html

- content/docs/reference-react.md
> docs(cn): fix speech error in reference-react.md

- content/docs/hooks-rules.md
> docs(cn): fix part of speech in content/docs/hooks-rules.md

- content/docs/components-and-props.md
> docs(cn): add a space between English work and Chinese in content/docs/components-and-props.md into Chinese

- content/docs/code-splitting.md
> docs(cn): fix typo

- content/docs/reference-glossary.md
> docs(cn): fix link in content/docs/reference-glossary.md

- content/blog/2020-05-22-react-hooks.md
> docs(cn): add new blog with hook

- content/docs/reconciliation.md
> docs(cn): optimize translation in content/docs/reconciliation.md

- content/docs/faq-ajax.md
> docs(cn): add new translate in content/docs/faq-ajax.md

- content/blog/2020-05-22-react-hooks.md
> docs(cn): update content/blog/2020-05-22-react-hooks.md

- content/docs/forms.md
> docs(cn): rm extra word in content/docs/forms.md

- content/docs/context.md
> docs(cn): optimize translation in content/docs/context.md

- content/blog/2020-05-22-react-hooks.md
> docs(cn): fix word spell in content/blog/2020-05-22-react-hooks.md

- content/docs/render-props.md
> docs(cn): optimize translation in content/docs/render-props.md

- content/blog/2020-08-10-react-v17-rc.md
> docs(blog): fix typo in content/blog/2020-08-10-react-v17-rc.md

- content/docs/introducing-jsx.md
> docs(cn): fix typo in content/docs/introducing-jsx.md

- content/docs/hooks-faq.md
This paragraph has not been translated into Chinese :)
> docs(cn): supplementary translation in content/docs/hooks-faq.md

- content/docs/hooks-faq.md
> docs(cn): fix translate in content/docs/hooks-faq.md

- content/docs/hooks-faq.md
> docs(cn): fix word in content/docs/hooks-faq.md

- content/blog/2020-02-26-react-v16.13.0.md
docs(cn): translate /content/blog/2020-02-26-react-v16.13.0.md into Chinese
> docs(cn): translate /content/blog/2020-02-26-react-v16.13.0.md into Chinese

- content/docs/cross-origin-errors.md
Add Chinese translation for content/docs/cross-origin-errors.md
Please review the translation and let me know if there are any changes needed.
> docs(cn):translate content/docs/cross-origin-errors.md

- content/blog/2020-08-10-react-v17-rc.md
Note to Hacktoberfest 🎃 participants:
While we appreciate the enthusiasm, we are experiencing a high volume of drive-by pull requests (one-line changes, README tweaks, etc.). Please remember that hundreds of people are subscribed to this repo and will receive notifications for these PRs. Spam submissions will be closed and won't count towards your Hacktoberfest goals.
Please search for issues tagged [`good first issue`][gfi] or [`hacktoberfest`][hacktoberfest] to find things to work on.
You can also search [all of GitHub][all].
[gfi]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[hacktoberfest]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[all]: …
> docs(cn): fix wrong translation content

- content/docs/reference-events.md
fix events docs `polyfil` -> `polyfill`
> docs(cn): fix word in content/docs/reference-events.md

- content/docs/uncontrolled-components.md
> docs(cn): fix word in content/docs/uncontrolled-components.md

- content/docs/introducing-jsx.md
> docs(cn): fix code in content/docs/introducing-jsx.md

- content/blog/2020-12-21-data-fetching-with-react-server-components.md
> chore: change video url to tencent

- content/docs/reference-react-component.md
> docs(cn): fix word in content/docs/reference-react-component.md

- content/docs/hooks-faq.md
> docs(cn): fix words in content/docs/hooks-faq.md

- content/blog/2018-06-07-you-probably-dont-need-derived-state.md
> docs(cn): fix words in content/blog/2018-06-07-you-probably-dont-need-derived-state.md

- content/blog/2020-10-20-react-v17.md
> docs(cn): fix words in content/blog/2020-10-20-react-v17.md

- content/docs/concurrent-mode-patterns.md
> docs(cn): fix typo in content/docs/concurrent-mode-patterns.md

- content/blog/2018-06-07-you-probably-dont-need-derived-state.md
change comment filter to filterText
> docs(cn): fix word in 2018-06-07-you-probably-dont-need-derived-state.md

- content/docs/hooks-faq.md
> docs(cn): fix typo error in content/docs/hooks-faq.md

- content/docs/typechecking-with-proptypes.md
> docs(cn): fix words in typechecking-with-proptypes.md

- content/docs/getting-started.md
> docs(cn): update getting-started.md

- content/docs/add-react-to-a-website.md
> docs(cn): update add-react-to-a-website.md

- content/docs/create-a-new-react-app.md
> docs(cn): update create-a-new-react-app.md

- examples/context/updating-nested-context-theme-toggler-button.js
Check the problem in 'content\docs\context.md': 
**theme-toggler-button.js**
`embed:context/updating-nested-context-theme-toggler-button.js`
> fix: format which causes unexpected problem

- content/docs/faq-functions.md
> docs(cn): fix words in content/docs/faq-functions.md

- content/docs/hooks-reference.md
> docs(cn): some improvements in hooks-reference

- content/docs/reference-events.md
> docs(cn): update reference-events.md

- content/docs/hooks-faq.md
> docs(cn): delete duplicate words. content/docs/hooks-faq.md

- content/tutorial/tutorial.md
> docs(cn): fix words in content/tutorial/tutorial.md

- content/docs/faq-functions.md
> docs(cn): fix document format in faq-functions.md

- content/docs/lists-and-keys.md
> docs(cn): fix words in lists-and-keys.md

- content/docs/introducing-jsx.md
> docs(cn): fix words in content/docs/introducing-jsx.md

- content/docs/state-and-lifecycle.md
> docs(cn): fix a punctuation typo in content/docs/state-and-lifecycle.md

- content/docs/reference-react.md
> docs(cn): additional description of state in  content/docs/reference-react.md

- content/docs/react-without-es6.md
**What happened？**
A link was misdirected.
> fix: link error in content/docs/react-without-es6.md

- content/docs/hooks-faq.md
> docs(cn): optimized translation in content/docs/hooks-faq.md

- content/docs/context.md
> docs(cn): optimized translation in content/docs/context.md

- beta/src/pages/learn/installation.md
> [Beta]: docs(cn): translate installation

- content/docs/state-and-lifecycle.md
> docs(cn): fix words in state-and-lifecycle.md

- content/docs/design-principles.md
> docs(cn): fix word in design-principles.md

- content/docs/design-principles.md
> docs(cn): fix words in design-principles.md

- content/tutorial/tutorial.md
> docs(cn): translate new sentence in tutorial

- content/docs/reference-react-component.md
> docs(cn): rm extra word in content/docs/reference-react-component.md

- beta/src/pages/learn/responding-to-events.md
> [Beta] docs(cn): improve coherence for responding-to-events.md

- content/docs/hooks-faq.md
> docs(cn): fix translation of "false positive"

- content/docs/reference-profiler.md
> docs(cn): restoration of the tree's quantifiers

- content/docs/hooks-reference.md
> docs(cn): fix translation of "useMemo"

- content/docs/reference-react.md
> docs(cn): update reference-react.md

- content/docs/strict-mode.md
> docs(cn): remove strict-mode.md

- content/docs/reference-react-dom.md
> docs(cn): fix words error

- content/docs/render-props.md
> docs(cn): optimising translation in render-props.md

- beta/src/pages/community/meet-the-team.md
- content/community/team.md
> [Beta] docs(cn): fix enhance translation

- beta/src/sidebarLearn.json
> [Beta] docs(cn): translate learn section menu

- README.md
> docs(cn): update the default branch in README.md

- content/docs/handling-events.md
> update: handling-events.md “显式的使用” > “显式地使用”

- content/blog/2022-06-15-react-labs-what-we-have-been-working-on-june-2022.md
I have translated the latest blog of React into Chinese, please review it and hope it can be adopted.
> docs(cn): translate content/blog/2022-06-15-react-labs-what-we-have-been-working-on-june-2022.md into Chinese

- beta/src/content/learn/editor-setup.md
更改前：如果自动格式化你的代码
更改后：如何自动格式化你的代码
> fix(cn): description error

- content/docs/reference-react-dom.md
> fix: change some details for ReactDOM

- content/docs/hello-world.md
> fix: correct the prev link

- content/docs/hello-world.md
- content/docs/introducing-jsx.md
> fix: change the previous English link to Chinese link

- content/docs/optimizing-performance.md
> fix typo in `optimizing-performance`

- content/community/videos.md
> fix translations in `community/videos`

- beta/src/components/Layout/Page.tsx
> fix: remove `<SocialBanner/>`

- beta/src/content/learn/updating-arrays-in-state.md
> fix(cn): heading level error

- src/sidebarBlog.json
- src/sidebarCommunity.json
- src/sidebarHome.json
- src/sidebarLearn.json
- src/sidebarReference.json
> docs(cn): update sidebar translations

- TRANSLATION.md
> chore: remove beta description

- src/components/Seo.tsx
- src/content/index.md
- src/pages/_document.tsx
> feat: optimize SEO

- .github/workflows/analyze.yml
This pull request just a test, will revert eventually.
> chore: fix workflow 

- .github/workflows/analyze.yml
- .github/workflows/analyze_comment.yml
> chore: fix workflows

- .github/workflows/analyze.yml
- .github/workflows/analyze_comment.yml
> chore: optmize

- .github/workflows/analyze_comment.yml
> fix(gh-workflow): update the action version

- .github/workflows/analyze_comment.yml
> chore: restore workflow format

- src/content/learn/state-as-a-snapshot.md
**state-as-a-snapshot**章节
```
<Challenges>
// ....
</Challenges>
```
组件中标题层级错误，导致进入页面时会自动跳转至页尾。
> fix(cn): corrected a heading level error

- src/content/learn/adding-interactivity.md
- src/content/learn/state-a-components-memory.md
> fix(cn): correct useState link

- src/content/learn/start-a-new-react-project.md
> docs(cn): fix learn/start-a-new-react-project

- src/content/reference/react-dom/components/select.md
翻译 reference/react-dom/components/select。
> docs(cn): translate reference/react-dom/components/select into Chinese

- src/content/reference/react-dom/server/index.md
翻译 reference/react-dom/server/index。
> docs(cn): translate reference/react-dom/server/index into Chinese

- src/content/reference/react-dom/components/progress.md
翻译 reference/react-dom/components/progress。
> docs(cn): translate reference/react-dom/components/progress into Chinese

- src/content/reference/react-dom/components/textarea.md
翻译 reference/react-dom/components/select
> docs(cn): translate reference/react-dom/components/textarea into Chinese

- src/content/reference/react/apis.md
翻译 reference/react/apis
@QC-L @Yucohny @awxiaoxian2020
> docs(cn): translate reference/react/apis into Chinese

- src/content/reference/react-dom/index.md
> docs(cn): translate react-dom/index into Chinese

- src/content/warnings/invalid-aria-prop.md
翻译：warnings/invalid-aria-prop。
> docs(cn): translate warnings/invalid-aria-prop into Chinese

- src/content/warnings/special-props.md
> docs(cn): translate warnings/special-props into Chinese

- src/content/learn/scaling-up-with-reducer-and-context.md
- src/sidebarLearn.json
modify `sidebarLearn.json` with already translated contents. @Yucohny
> docs(cn): translate src/sidebarLearn.json into Chinese

- src/content/reference/react-dom/components/textarea.md
> docs(cn): update reference/react-dom/components/textarea translation

- src/content/reference/react/useCallback.md
翻译 reference/react/useCallback。
> docs(cn): translate reference/react/useCallback into Chinese

- src/content/reference/react/Profiler.md
更新 reference/react/profiler 翻译。
更新内容主要为调整表达，以让表达更加通顺，同时避免读者误解。
> docs(cn): update reference/react/profiler translation

- src/content/reference/react/directives.md
调整 reference/react/directives 翻译。
> docs(cn): update reference/react/directives translation

- src/content/reference/react/useMemo.md
优化 reference/react/useMemo 翻译。
优化的点主要包括：
（1）调整表达，使其更加通顺；
（2）修正翻译错误的地方（见评论）。
> docs(cn): optimize reference/react/useMemo translation

- src/sidebarLearn.json
> docs(cn):  keep the sidebar the same as the title

- src/sidebarBlog.json
> docs(cn): translate sidebarBlog into Chinese

- src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
翻译 blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022。
> docs(cn): translate blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022 into Chinese

- src/content/learn/thinking-in-react.md
> fix: adjust some format

- src/content/reference/react-dom/createPortal.md
> docs(cn): update react-dom/createPortal translation and translate text in code

- src/content/community/team.md
> docs(cn): translate community/team into Chinese

- src/content/reference/react-dom/createPortal.md
Reverts reactjs/zh-hans.react.dev#1272
> Revert "docs(cn): update react-dom/createPortal translation and translate text in code"

- src/content/learn/synchronizing-with-effects.md
> docs(cn): update learn/synchronizing-with-effects typo

- src/content/reference/react-dom/createPortal.md
> docs(cn): improve react-dom/createPortal translation and translate text in code

- src/content/reference/react-dom/components/common.md
优化 reference/react-dom/component/common 翻译，并调整格式。
> docs(cn): improve reference/react-dom/component/common translation and adjust format

- src/content/learn/typescript.md
> docs(cn): translate learn/typescript into Chinese

- src/content/learn/typescript.md
> docs(cn): improve learn/typescript translation

- src/content/learn/reusing-logic-with-custom-hooks.md
> docs(cn): improve learn/reusing-logic-with-custom-hooks translation

- src/content/reference/react/use.md
> docs(cn): translate reference/react/use into Chinese

- src/content/reference/react/index.md
翻译 reference/react/index 新增内容。
> docs(cn): translate the added content of reference/react/index into Chinese

- src/content/blog/index.md
- src/content/learn/start-a-new-react-project.md
- src/sidebarBlog.json
> docs(cn): update the Chinese translation for RSCs

- src/content/reference/react/use-client.md
- src/content/reference/react/use-server.md
翻译 reference/react/use-client 与 reference/react/use-server 新增内容。
> docs(cn): translate the added content of reference/react/use-client&use-server into Chinese

- src/content/reference/react-dom/client/index.md
- src/content/reference/react-dom/server/index.md
优化 reference/react-dom/server/index 与 reference/react-dom/client/index 翻译。
> docs(cn): improve reference/react-dom/server/index and reference/react-dom/client/index translation

- src/components/MDX/Challenges/Challenge.tsx
英文原文为Next Example/Challenge，Next漏译
> fix: correct translation in Challenge component

- src/content/community/team.md
> docs(cn): fix community/team format

- src/content/learn/render-and-commit.md
> fix: typo in learn/render-and-commit.md

- src/content/learn/thinking-in-react.md
> docs(cn): improve learn/think-in-react translation

- src/content/learn/describing-the-ui.md
翻译 learn/describing-the-ui 新增内容。
> docs(cn): translate the new content of learn/describing-the-ui into Chinese

- src/content/learn/preserving-and-resetting-state.md
翻译 learn/preserving-and-resetting-state 新增内容。
> docs(cn): translate the new content of learn/preserving-and-resetting-state into Chinese

- src/content/reference/react/useRef.md
> docs(cn): improve the translation of reference/react/useRef

- src/content/reference/react-dom/hooks/useFormState.md
将 Server Actions 修改为 Server Action。
> chore(singular): replace Actions with Action

- src/content/reference/react/createContext.md
> docs(cn): improve reference/react/createContext translation

- src/content/learn/synchronizing-with-effects.md
> fix: fix misspelled words

- src/content/reference/react/useSyncExternalStore.md
翻译 reference/react/useSyncExternalStore 新增内容。
> docs(cn): translate the new content of reference/react/useSyncExternalStore

- src/content/reference/react/forwardRef.md
优化 reference/react/forwardRef 翻译。
> docs(cn): improve translations of reference/react/forwardRef

- src/content/learn/manipulating-the-dom-with-refs.md
\- Finally, pass your ref as the `ref` attribute to the JSX tag for which you want to get the DOM node:
\+ 最后，将你的 ref 作为 `ref` 属性传递给你想要获取 DOM 节点的 JSX 标签：
> feat: finish the untranslated part

- src/components/Layout/Toc.tsx
- src/utils/prepareMDX.js
> docs(cn): translate the content of sidebar

- src/content/reference/react/index.md
> fix: Unified translation, correct punctuation and capitalization

- src/content/reference/react/experimental_taintObjectReference.md
- src/content/reference/react/experimental_taintUniqueValue.md
> fix(cn): restore translations

- src/content/learn/rendering-lists.md
> fix: resolve incorrect directory

- src/content/reference/react/useCallback.md
> fix(useCallback) : remove redundant text

- src/sidebarLearn.json
> docs(cn): translate sidebar

- src/content/reference/react-dom/components/meta.md
翻译 reference/react-dom/components/meta。
> docs(cn): translate reference/react-dom/components/meta into Chinese

- src/content/reference/react-dom/preinitModule.md
翻译 reference/react-dom/preinitModule。
> docs(cn): translate reference/react-dom/preinitModule into Chinese

- src/content/blog/index.md
- src/sidebarBlog.json
> update: 翻译漏掉的博客相关内容

- src/content/reference/react-dom/hooks/useFormStatus.md
> chore: sync `useFormStatus`

- src/content/learn/writing-markup-with-jsx.md
> docs: update writing-markup-with-jsx translation

- src/content/learn/keeping-components-pure.md
- 翻译了 /learn/keeping-components-pure中未被翻译的代码注释
> docs(cn): translated code comments in keeping-components-pure into Chinese

- src/sidebarLearn.json
> fix: fix the inconsistency between the sidebar and the title

- src/content/learn/adding-interactivity.md
- src/content/learn/describing-the-ui.md
- src/content/learn/escape-hatches.md
- src/content/learn/managing-state.md
> docs: update the subheadings in the abstract

- src/content/reference/react/useInsertionEffect.md
> docs(cn): translate the missing part in useInsertionEffect.md

- src/content/reference/react/useLayoutEffect.md
> docs(cn): translate the missing part in useLayoutEffect.md

- src/content/reference/rules/index.md
> docs(cn): translate reference/rules/index.md into Chinese

- src/content/learn/rendering-lists.md
fix https://github.com/reactjs/zh-hans.react.dev/issues/1527
> fix: translate names in code block

- src/content/learn/state-as-a-snapshot.md
> fix: translate code

- src/content/blog/2024/04/25/react-19.md
- src/content/reference/react/useActionState.md
> fix: correct useActionState to useFormState in react-19 and useActionState

- src/content/learn/synchronizing-with-effects.md
文档中部分代码示例存在漏翻，参考文档中的其他段落做了补全：
Pause -> 暂停
Play -> 播放
Calling -> 调用
> docs(cn): improve learn/synchronizing-with-effects translation 

- src/content/learn/manipulating-the-dom-with-refs.md
> fix: add missing translation

- src/content/learn/choosing-the-state-structure.md
> fix: 将“字母”替换成“信件”

- src/content/learn/start-a-new-react-project.md
Hello @Nkevi @loveloki,
I must congratulate you and the whole team on the translation work. I'm glad to see many fellow translators who are helping community. I just started translating [Serbian version](https://github.com/reactjs/sr.react.dev) and I must admit it's a bunch of work.
I've created this PR based on the issue (https://github.com/reactjs/react.dev/issues/7164) on main repo which I noticed few days ago.
Since I don't speak chinese, I hope you're ok with me contributing to this repo :wink:
I wish you all luck with maintaining and improving this repo :rocket:
> Fix link in start-a-new-react-project.md

- src/content/learn/reusing-logic-with-custom-hooks.md
original: `ltimately you decide where to draw the boundaries between different parts of your code`
> refactor: more semantic translation, avoid misunderstanding

- src/content/learn/escape-hatches.md
Display the original English text whenever ’脱围机制（escape hatches）' are encountered for the first time.
> 📃 docs(cn): improve escape_hatches

- src/content/blog/index.md
align with English doc version
> fix wrong release date of React v19

- src/content/learn/adding-interactivity.md
- src/content/learn/describing-the-ui.md
- src/content/learn/extracting-state-logic-into-a-reducer.md
- src/content/learn/index.md
- src/content/learn/javascript-in-jsx-with-curly-braces.md
- src/content/learn/keeping-components-pure.md
- src/content/learn/managing-state.md
- src/content/reference/react-dom/server/renderToPipeableStream.md
There are still many English sections remaining in previously translated articles, maybe due to updates in the original text or oversights in earlier translations. 
And this PR translates these sections
> doc(cn): translate some previously English sections

- .github/workflows/analyze.yml
> fix(gh-workflows): bump version

- src/content/learn/creating-a-react-app.md
> feat: creating-a-react-app

- src/content/reference/react/useSyncExternalStore.md
> fix: the translation of the subscribe parameter in useSyncExternalStore

- src/content/reference/react-compiler/gating.md
[translate page link](https://zh-hans.react.dev/reference/react-compiler/gating)
> docs(cn): translate gating.md into Chinese
